script:
language: php
sudo: false
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - phpenv config-add xdebug.ini
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --no-interaction

script:
  - php vendor/bin/phpcs --standard=psr2 CollectionJson
  - php vendor/bin/phpunit --configuration tests/phpunit.xml tests

after_script:
  - php vendor/bin/coveralls
